name: what-if

on:
  pull_request:
    paths: arm/*.json
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script file
      uses: azure/CLI@v1
      env:
        AZURE_CORE_NO_COLOR: True
      with:
        inlineScript: |
          az deployment group what-if --no-prompt --resource-group what-if-demo --template-file $GITHUB_WORKSPACE/arm/template.json --parameters $GITHUB_WORKSPACE/arm/parameters.json --mode Complete | tee -a what-if.log
    
    - uses: actions/github-script@v1
      with:
        script: |
          const fs = require('fs')
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "The deployment will do the following changes:\n```\n" + fs.readFileSync("what-if.log", "ascii") + "```"
          })
