name: what-if

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group what-if --resource-group what-if-demo --template-file $GITHUB_WORKSPACE/arm/template.json --parameters $GITHUB_WORKSPACE/arm/parameters.json --mode Complete 2>&1 | tee -a what-if.log

    - name: Set log
      run: echo "::set-output name=what-if::$(cat what-if.log)"
    
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@master
      with:
        message: "''''''"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
